CC=g++ -std=c++11
all: knn cc
knn:compute_knn_movie_test.cpp
	$(CC) -o knn ./compute_knn_movie_test.cpp	
cc:compute_correlation_between_movies.cpp
	$(CC) -o cc ./compute_correlation_between_movies.cpp
